### ISSUE TITLE
go install latest produces incorrect binary

### ISSUE THREAD

**Issue by tekicode** [FUSAKLA/promruval#29]
# Issue
Current installation instructions are no longer valid. `go get` is not a valid command outside of a module. `go install` produces a version of the tool that is not expected. References to `v2` are not valid.

```
❯ go install github.com/fusakla/promruval@latest
❯ promruval version
Version: dev
Build date: 2022-12-19
Build commit: none
Built by: teki
❯ promruval --help
usage: promruval [<flags>] <command> [<args> ...]

Prometheus rules validation tool.

Flags:
--help  Show context-sensitive help (also try --help-long and --help-man).

Commands:
help [<command>...]
Show help.

version
Print version and build information.

validate --config-file=CONFIG-FILE [<flags>] <path>...
Validate Prometheus rule files using validation rules from config file.

validation-docs --config-file=CONFIG-FILE [<flags>]
Print human readable form of the validation rules from config file.
❯ go install github.com/fusakla/promruval/v2@latest
go: github.com/fusakla/promruval/v2@latest: module github.com/fusakla/promruval@latest found (v1.3.2), but does not contain package github.com/fusakla/promruval/v2
```

Expect the latest available version to be installed when `go install ...@latest` is used

**Comment by FUSAKLA** [comment]
Hi, thanks for rising the issue!
 I believe this is the same issue as reported here https://github.com/FUSAKLA/promruval/issues/28

I'll close this one, but feel free to reopen it, if you see it a different way.

**Comment by FUSAKLA** [comment]
Ok, just released new version and `go install github.com/fusakla/promruval/v2@latest` should be working now if you could verify? :pray:

**Comment by tekicode** [comment]
Works now, thank you for the help!

**Comment by FUSAKLA** [comment]
Grat, thanks for reporting! :)
