### ISSUE TITLE
validate that an expressions uses metric name

### ISSUE THREAD

**Issue by tizki** [FUSAKLA/promruval#33]
very nice project!
I want to be able to validate the the expressions of alerting rules use metric name (to avoid getting results from ALERT / ALERTS_FOR_STATE for example).
is it possible to do it with the existing validators? if not, any chance it can be added?
Thanks!

**Comment by FUSAKLA** [comment]
Hi and thank you!
U
nfortunately current validators cannot test that, but it should be quite easy to add such validator and sounds reasonable to me :+1: 

I'll take a look at it when I find a free while, or feel free to send PR if you want to speed things up
