### ISSUE TITLE
Support for `commaSeparatedValue` on `annotationHasAllowedValue`

### ISSUE THREAD

**Issue by neufeldtech** [FUSAKLA/promruval#5]
Hi,
Would you consider adding support for the `commaSeparatedValue` feature on the `annotationHasAllowedValue` validator just as it exists on the `labelHasAllowedValue` validator?

**Comment by FUSAKLA** [comment]
Hi, yeah I thought about that formerly and thought that annotations will be probably more unstructured.
But yeah I don't see the reason not to. :) 

PTAL https://github.com/FUSAKLA/promruval/pull/6
